apiVersion: v1
kind: Service
metadata:
  name: eureka-svc
spec:
  selector:
    app: eureka-sts
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  clusterIP: None

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: eureka-sts
  name: eureka-sts
spec:
  serviceName: eureka-svc
  replicas: 3
  selector:
    matchLabels:
      app: eureka-sts
  template:
    metadata:
      labels:
        app: eureka-sts
    spec:
      containers:
        - image: eureka-server
          name: eureka
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: EUREKA_INSTANCE_HOSTNAME
              value: ${HOSTNAME}.eureka
            - name: EUREKA_INSTANCE_LIST
              value: "http://eureka-sts-0.eureka-svc.default.svc.cluster.local:8761/eureka/,http://eureka-sts-1.eureka-svc.default.svc.cluster.local:8761/eureka/,http://eureka-sts-2.eureka-svc.default.svc.cluster.local:8761/eureka/"

